### ISSUE TITLE
Greedy script?

### ISSUE THREAD

**Issue by ZzZombo** [pie6k/jquery.initialize#17]
```
var observer = new MutationObserver(function (mutations) {

        // For each MutationSelectorObserver currently registered.
        for (var j = 0; j < msobservers.length; j++) {
            $(msobservers[j].selector).each(msobservers[j].callback);
        }
    });
```

If I read the code right, nowhere there the `mutations` variable is ever referenced. How does the script work then? Does it mean that for **all** mutations it subscribed to to **all** elements in the document, it will run callbacks? Huh? That explains the huge performance hit I witness ever since I added the script to my userscript.

**Comment by dbezborodovrp** [comment]
Hi @ZzZombo. Your performance issue sounds plausible. I'll be looking into it soon.

**Comment by dbezborodovrp** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by dbezborodovrp** [comment]
There are a few issues here (without delving into the code):

1) Subscription to all mutations. According to document, there are three mutation types: `childList`, `attributes`, or `characterData`. The script needs to observe `attributes` for situations such as when the `class` or `id` attributes are changed. `childList` must be observed for when a new element is added to the document. We could probably ignore `characterData`, so we can change that.

2) The entire document is observed. There is the possibility to add extra options to limit this to specific elements, such as `<body>` or the main container `<div>`, etc. This isn't a major issue anyhow.

3) When a mutation is observed, we search the entire document for matching elements. This could be limited to the element where the mutation observed. However, this could break selectors that use [child](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors) or [descendant combinators
](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_selectors). So, this would probably need to be an optional feature to ensure backward compatibility.

**Comment by ZzZombo** [comment]
This shouldn't break anything. Nodes are already inserted/removed by the time an observer handles such actions. Same goes for all the other event types.

**Comment by pati610** [comment]
@ZzZombo I have 50+ selectors registered, and have no impacts on performance whatsoever. Are you sure that you're only initializing your selectors once? Because if they get reinitialized, let's say at partial loads on a dynamic page, that will choke the page in no time.

I know this from my own experience, because I have to do just that - detect newly inserted DOM elements at every partial ajax page load. The site went crazy when selectors were registered. I wrote a deInitialize func, removing either all or defined selectors, that I attached to a jQuery on hashchange callback. Works great!

@pie6k I'll fork your script and then I'll make a pull request, you are free to incorporate my added func as you see fit (if at all.)

**Comment by dbezborodovrp** [comment]
Hi @ZzZombo, please see #19.

Usage is as follows:

```
$.initialize.defaults.scanDocument = false;
$.initialize('.initialize-me', function() {
    $(this).css('color', 'blue');
});
```

Or:

```
$.initialize('.initialize-me', function() {
    $(this).css('color', 'blue');
}, {scanDocument: false});
```

This will have the effect of only scanning `MutationRecord.addedNodes` ([MutationRecord](https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord)) instead of the entire `document.documentElement` tree for matching selectors.

This feature must be an option, because some users may use selectors that rely on parent elements. Therefore, to maintain backward compatibility, we must scan the entire document by default for cases such as these. For example, selectors such as `.parent-node .initialize-me` would be broken if `scanDocument` is `true` and the mutation occurs on a child of `.parent-node` rather than on `.parent-node` itself.

----

Mutations other than `['childList', 'attributes']` are ignored (such as `characterData`.)

----

The entire document is still observed, however. See:

```
observer.observe(document.documentElement, {childList: true, subtree: true, attributes: true});
```

To make this configurable would break backward compatibility, so I'd suggest opening a separate Issue if you insist on this feature.

**Comment by dbezborodovrp** [comment]
The third feature has also now been implemented in #19.

**Comment by dbezborodovrp** [comment]
Further improvements in #21.

@ZzZombo If you are interested in testing, please test the branch in #21, `dbezborodovrp:feature/autoperf`

To test via NPM
```
npm install github:dbezborodovrp/jquery.initialize#feature/autoperf --save && npm install
```

**Comment by ZzZombo** [comment]
You made the wrong call. Please read the API specs, or just do a simple test with debug output to browser console. When MutationObserver fires a callback, all changes in the batch it provides have ALREADY executed, *as I have said it so in my first response* 😩. That's why you are provided with the changed element and optionally `**old**-whatever` attribute values and not the other way around, element to be changed, and `**new**-something` values. Therefore, your fix in this manner is pointless, and doesn't improve anything

**Comment by dbezborodovrp** [comment]
Have you seen and tested the changes?

I'm not sure I follow your reasoning. I know that the element has already been mutated before the observer sees it. That's not a problem. If fact, if the change were not visible, then it would be impossible to query the mutated nodes for matches. So, this seems completely irrelevant to me.

I may have not explained my changes correctly. Disregard the above. I will explain it afresh.

What I have done in #19 and #21 is to address the following concerns:

> Does it mean that for all mutations

The plugin now ignores mutation types that are not `childList` or `attributes`

> it subscribed to to all elements in the document

By default, the plugin will observe all elements (that is, `document.documentElement`. However, you can now override this by specifying an element. For example:

```
$.initialize.defaults.target = document.getElementById('observe-this-element');
```

Or:

```
$.initialize('div.foo', callbackFunction, { target: document.getElementById('observe-this-element') });
```

---

Furthermore, the plugin will not query the entire document for nodes matching the selector. It will only check the mutated node for a match (or its descendants or parents depending upon the complexity of the selector.)

**Comment by dbezborodovrp** [comment]
Did you want to be able to set `attributeOldValue` to true in the `MutationObserverInit` options? I can expose that if that is what you are after.

**Comment by ZzZombo** [comment]
`$.initialize.defaults.scanDocument = false;` is not needed is all I say.

**Comment by dbezborodovrp** [comment]
I agree. I removed that in #21.

**Comment by ZzZombo** [comment]
Then great. Hope to use the updated version in a project soon.

**Comment by dbezborodovrp** [comment]
Very good. The performance improvements haven't been released yet. If you want to test with your application, please do so by installing the test branch:

```
npm install github:dbezborodovrp/jquery.initialize#feature/autoperf --save && npm install
```

I also exposed observer options in 573fb610d9ae89cd9b5fd34937388f91c78d4cb1

**Comment by dbezborodovrp** [comment]
These performance changes have been release under 1.2.0.
