### ISSUE TITLE
Getting element `index` out of the `$.initialize` loop.

### ISSUE THREAD

**Issue by IrvingArmenta-ML** [pie6k/jquery.initialize#30]
Hello, I'm trying to get the index number of the elements out in the `$.initialize` loop, like this: 

```
$.initialize('.element', function(i,el) { 
  console.log(i) // this always return: 0 
});
```
What I want to achieve, is the same functionality as `$.each` or `$.map` to count and distinguish the elements in the DOM, but I keep getting `0` on `index`, however the `DOM nodes` are shown correctly on `el`.

Is there a solution for this?

**Comment by pie6k** [comment]
I think concept of element index is not relevant here as it's calling this callback as soon as element has appeared on the screen, so it has no context of 'group' like `map` or `each` has.

Consider such case

Initially you have 5 `.element` divs
Then you add 2 more `.element` divs
Then you **remove** 3 of existing `.element` divs
Then you add one more ----> what would you expect now to be `i` inside this function?

**Comment by dbezborodovrp** [comment]
An iterator doesn't exactly make sense in this context since elements can be inserted into the DOM out of order, and also can appear in complex or nested trees, not just as siblings.

If you are insistent on this, you can off course do:

```
var i = 0;
$.initialize('.element', function(el) { 
  console.log(i);
  i++;
});
```

Although I understand that it may make sense to have an iterator in some circumstances, nobody has asked for such a feature to date.  I wonder for the sake of curiosity what your scenario is that you need this for?

**Comment by dbezborodovrp** [comment]
Wontfix.
